version: @project.version@
server:
  port: 8080
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: bing-image
bing:
  domain: https://www.bing.com
image:
  folder: ${IMAGE_FOLDER}
  auto:
    cron: ${IMAGE_AUTO_CRON}
log:
  path: ${LOG_PATH}
aliyun:
  ddns:
    region-id: ${ALIYUN_DDNS_REGION-ID}
    access-key: ${ALIYUN_DDNS_ACCESS-KEY}
    access-key.secret: ${ALIYUN_DDNS_ACCESS-KEY_SECRET}
    sub-domain-list: ${ALIYUN_DDNS_SUB-DOMAIN-LIST}
    sub-domain-split-regex: ${ALIYUN_DDNS_SUB-DOMAIN-SPLIT-REGEX}